---
- name: add rabbitmq vhost
  rabbitmq_vhost: name={{ item }} state=present
  with_items: rabbitmq_vhost_definitions

- name: add rabbitmq user and set priveleges
  rabbitmq_user:
    user={{ item.user }}
    password="{{ item.password }}"
    vhost={{ item.vhost | default('/', false) }}
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
    force=yes
  with_items: rabbitmq_users_definitions

- name: remove guest user
  rabbitmq_user:
    user=guest
    vhost=/
    state=absent
