---
- hosts: rabbit-standalone
  roles:
    - role: rabbitmq
      rabbitmq_ssl: false
      rabbitmq_conf_tcp_listeners_address: '0.0.0.0'
      rabbitmq_vhost_definitions:
        - sensu
      rabbitmq_users_definitions:
        - vhost   : sensu
          user    : sensu
          password: placeholder
      rabbitmq_federation: true
      rabbitmq_federation_configuration:
        - name: test
          vhost: sensu
          value: '{"uri" : "amqp://server-name", "expires" : 3600000}'
      rabbitmq_policy_configuration:
        - name: policy
          pattern: '.'
          vhost: sensu
          tags: "federation-upstream-set=all"
  tasks:
    - include: test_standalone.yml
